name: Execução de testes funcionais

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 9,11,15,18 * * 1,2,3,4,5'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
     
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          command:  npm run cypress:open

   
    
