name: Execução de testes funcionais
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 9,11,15,18 * * 1,2,3,4,5'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
     
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          record: true
        env:
          CYPRESS_RECORD_KEY: 105a9675-a503-406b-93c8-0c8ab7fa39c6
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
